[buildPlans.iosevka-kagami-fs]
family = "Iosevka Kagami (F#)"
design = ["sans", "ligset-fs", "cv02", "cv03", "cv07", "cv11", "cv13", "cv17", "cv18", "cv21", "cv22", "cv25", "cv29", "cv32", "cv35", "cv37", "cv39", "cv40", "cv42", "cv45", "cv47", "cv48", "cv51", "cv52", "cv62"]
upright = []
italic = []
oblique = []